[program]
prods = [
    ["node_nt", "program"],
    [""]
]
first = ["node", ""]
follow = ["$"]

[node_nt]
prods = [
    ["node", "node_header", "node_block"]
]
first = ["node"]
follow = ["node", "$"]

[node_header]
prods = [
    ["id", "opt_id_list"]
]
first = ["IDENTIFIER"]
follow = ["{"]

[opt_node_list]
prods = [
    [":", "node_list"],
    [""]
]
first = [":", ""]
follow = ["{"]

[node_list]
prods = [
    ["id", "node_rest"]
]
first = ["IDENTIFIER"]
follow = ["{"]

[node_rest]
prods = [
    [",", "node_list"],
    [""]
]
first = [",", ""]
follow = ["{"]

[node_block]
prods = [
    ["{", "top_level_stmt_list", "}"]
]
first = ["{"]
follow = ["node", "$"]

[top_level_stmt_list]
prods = [
    ["top_level_stmt", "top_level_stmt_list"],
    [""]
]
first = ["fn", ""]
follow = ["}"]

[top_level_stmt]
prods = [
    ["func"]
]
first = ["fn"]
follow = ["fn", "}"]

[func]
prods = [
    ["fn", "id", "(", "param_list", ")", "->", "return_type", "block"]
]
first = ["fn"]
follow = ["$"]

[return_type]
prods = [
    ["id"],
    ["(", ")"],
    ["!"]
]
first = ["IDENTIFIER", "(", "!"]
follow = ["{"]

[param_list]
prods = [
    ["param", "param_rest"],
    [""]
]
first = ["IDENTIFIER", ""]
follow = [")"]

[param]
prods = [
    ["id", ":", "id"],
]
first = ["IDENTIFIER"]
follow = [",", ")"]

[param_rest]
prods = [
    [",", "param_list"],
    [""]
]
first = [",", ""]
follow = [")"]

[block]
prods = [
    ["{", "stmt_list", "}"]
]
first = ["{"]
follow = ["$"]

[stmt_list]
prods = [
    ["stmt", "stmt_list"],
    [""]
]
first = ["var", "const", "IDENTIFIER", "while", "if", "return", ""]
follow = ["}"]

[stmt]
prods = [
    ["var", "id", ":", "id", "=", "expression", ";"],
    ["const", "id", ":", "id", "=", "expression", ";"],
    ["id", "=", "expression", ";"],
    ["while", "conditional", "block"],
    ["if", "conditional", "block", "optelse"],
    ["return", "expression", ";"],
]
first = ["var", "const", "IDENTIFIER", "while", "if", "return"]
follow = ["var", "const", "IDENTIFIER", "while", "if", "return", "}"]

[optelse]
prods = [
    ["else block"],
    [""]
]
first = ["else", ""]
follow = ["var", "const", "IDENTIFIER", "while", "if", "}"]

[expression]
prods = [
    ["term", "expression1"]
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = [")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[expression1]
prods = [
    ["+", "term", "expression1"],
    ["-", "term", "expression1"],
    [""]
]
first = ["+", "-", ""]
follow = [")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[term]
prods = [
    ["factor", "term1"]
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = ["+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[term1]
prods = [
    ["*", "factor", "term1"],
    ["/", "factor", "term1"],
    [""]
]
first = ["*", "/", ""]
follow = ["+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[factor]
prods = [
    ["(", "expression", ")"],
    ["id", "id_or_fn"],
    ["NUMBER"]
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = ["*", "/", "+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[id_or_fn]
prods = [
    ["(", "input_list", ")"],
    [""]
]
first = ["(", ""]
follow = ["*", "/", "+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[id]
prods = [
    ["IDENTIFIER"]
]
first = ["IDENTIFIER"]
follow = [")", "+", "-", "*", "/", ";", ":", "=", "(", "{"]

[input_list]
prods = [
    ["expression", "input_rest"],
    [""]
]
first = ["(", "IDENTIFIER", "NUMBER", ""]
follow = [")"]

[input_rest]
prods = [
    [",", "id_list"],
    [""]
]
first = [",", ""]
follow = [")"]

[conditional]
prods = [
    ["bool_expr", "conditional1"]
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = ["{"]

[conditional1]
prods = [
    ["&&", "bool_expr", "conditional1"],
    ["||", "bool_expr", "conditional1"],
    [""]
]
first = ["&&", "||", ""]
follow = ["{"]

[bool_expr]
prods = [
    ["expression", "comparison", "expression"],
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = ["&&", "||", "{"]

[comparison]
prods = [
    ["=="],
    ["!="],
    ["<"],
    [">"],
    ["<="],
    [">="],
]
first = ["==", "!=", "<", ">", "<=", ">="]
follow = ["(", "IDENTIFIER", "NUMBER"]