[block]
prods = [
    ["{", "stmt_list", "}"]
]
first = ["{"]
follow = ["$"]

[stmt_list]
prods = [
    ["stmt", "stmt_list"],
    [""]
]
first = ["var", "const", "IDENTIFIER", "while", "if", ""]
follow = ["}"]

[stmt]
prods = [
    ["var", "id", ":", "id", "=", "expression", ";"],
    ["const", "id", ":", "id", "=", "expression", ";"],
    ["id", "=", "expression", ";"],
    ["while", "conditional", "block"],
    ["if", "conditional", "block", "optelse"],
]
first = ["var", "const", "IDENTIFIER", "while", "if"]
follow = ["var", "const", "IDENTIFIER", "while", "if", "}"]

[optelse]
prods = [
    ["else block"],
    [""]
]
first = ["else", ""]
follow = ["var", "const", "IDENTIFIER", "while", "if", "}"]

[expression]
prods = [
    ["term", "expression1"]
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = [")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[expression1]
prods = [
    ["+", "term", "expression1"],
    ["-", "term", "expression1"],
    [""]
]
first = ["+", "-", ""]
follow = [")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[term]
prods = [
    ["factor", "term1"]
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = ["+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[term1]
prods = [
    ["*", "factor", "term1"],
    ["/", "factor", "term1"],
    [""]
]
first = ["*", "/", ""]
follow = ["+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[factor]
prods = [
    ["(", "expression", ")"],
    ["id"],
    ["NUMBER"]
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = ["*", "/", "+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "{"]

[id]
prods = [
    ["IDENTIFIER"]
]
first = ["IDENTIFIER"]
follow = [")", "+", "-", "*", "/", ";", ":", "="]

[conditional]
prods = [
    ["bool_expr", "conditional1"]
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = ["{"]

[conditional1]
prods = [
    ["&&", "bool_expr", "conditional1"],
    ["||", "bool_expr", "conditional1"],
    [""]
]
first = ["&&", "||", ""]
follow = ["{"]

[bool_expr]
prods = [
    ["expression", "comparison", "expression"],
]
first = ["(", "IDENTIFIER", "NUMBER"]
follow = ["&&", "||", "{"]

[comparison]
prods = [
    ["=="],
    ["!="],
    ["<"],
    [">"],
    ["<="],
    [">="],
]
first = ["==", "!=", "<", ">", "<=", ">="]
follow = ["(", "IDENTIFIER", "NUMBER"]