[program]
prods = [
    ["node_nt", "program"],
    [""]
]
first = ["node", ""]
follow = ["$"]

[node_nt]
prods = [
    ["node", "node_header", "node_block"]
]
first = ["node"]
follow = ["node", "$"]

[node_header]
prods = [
    ["id", "opt_id_list"]
]
first = ["IDENTIFIER"]
follow = ["{"]

[opt_node_list]
prods = [
    [":", "node_list"],
    [""]
]
first = [":", ""]
follow = ["{"]

[node_list]
prods = [
    ["id", "node_rest"]
]
first = ["IDENTIFIER"]
follow = ["{"]

[node_rest]
prods = [
    [",", "node_list"],
    [""]
]
first = [",", ""]
follow = ["{"]

[node_block]
prods = [
    ["{", "top_level_stmt_list", "}"]
]
first = ["{"]
follow = ["node", "$"]

[top_level_stmt_list]
prods = [
    ["top_level_stmt", "top_level_stmt_list"],
    [""]
]
first = ["fn", "export", "struct", ""]
follow = ["}"]

[top_level_stmt]
prods = [
    ["struct", "id", "{", "param_list", "}"],
    ["export", "definition"],
    ["func"]
]
first = ["fn", "export", "struct"]
follow = ["fn", "export", "struct", "}"]

[func]
prods = [
    ["fn", "id", "(", "param_list", ")", "->", "return_type", "block"]
]
first = ["fn"]
follow = ["$"]

[return_type]
prods = [
    ["type"],
    ["(", ")"],
    ["!"]
]
first = ["IDENTIFIER", "int", "float", "char", "bool", "(", "!"]
follow = ["{"]

[param_list]
prods = [
    ["param", "param_rest"],
    [""]
]
first = ["IDENTIFIER", ""]
follow = [")", "}"]

[param]
prods = [
    ["id", ":", "type"],
]
first = ["IDENTIFIER"]
follow = [",", ")"]

[param_rest]
prods = [
    [",", "param_list"],
    [""]
]
first = [",", ""]
follow = [")", "}"]

[block]
prods = [
    ["{", "stmt_list", "}"]
]
first = ["{"]
follow = ["$"]

[stmt_list]
prods = [
    ["stmt", "stmt_list"],
    [""]
]
first = ["var", "const", "IDENTIFIER", "while", "if", "return", ""]
follow = ["}"]

[stmt]
prods = [
    ["definition"],
    ["id", "assign_or_fn_call"],
    ["while", "conditional", "block"],
    ["if", "conditional", "block", "optelse"],
    ["return", "conditional", ";"],
]
first = ["var", "const", "IDENTIFIER", "while", "if", "return"]
follow = ["var", "const", "IDENTIFIER", "while", "if", "return", "}"]

[assign_or_fn_call]
prods = [
    ["opt_index", "=", "cond_or_arr", ";"],
    ["(", "input_list", ")", ";"]
]
first = ["=", "(", "["]
follow = ["var", "const", "IDENTIFIER", "while", "if", "return", "}"]

[opt_index]
prods = [
    ["[", "expression", "]", "opt_index"],
    [""]
]
first = ["[", ""]
follow = ["="]

[optelse]
prods = [
    ["else block"],
    [""]
]
first = ["else", ""]
follow = ["var", "const", "IDENTIFIER", "while", "if", "return", "}"]

[expression]
prods = [
    ["term", "expression1"]
]
first = ["(", "IDENTIFIER", "-", "INTEGER", "FLOAT", "true", "false", "CHARACTER"]
follow = [")", ";", "==", "!=", "<", ">", "<=", ">=", "&&", "||", "{", ",", "]"]

[expression1]
prods = [
    ["+", "term", "expression1"],
    ["-", "term", "expression1"],
    [""]
]
first = ["+", "-", ""]
follow = [")", ";", "==", "!=", "<", ">", "<=", ">=", "&&", "||", "{", ",", "]"]

[term]
prods = [
    ["factor", "term1"],
    ["CHARACTER"]
]
first = ["(", "IDENTIFIER", "-", "INTEGER", "FLOAT", "true", "false", "CHARACTER"]
follow = ["+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "&&", "||", "{", ",", "]"]

[term1]
prods = [
    ["*", "factor", "term1"],
    ["/", "factor", "term1"],
    [""]
]
first = ["*", "/", ""]
follow = ["+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "&&", "||", "{", ",", "]"]

[factor]
prods = [
    ["(", "expression", ")"],
    ["id", "id_rest"],
    ["primitive"]
]
first = ["(", "IDENTIFIER", "-", "INTEGER", "FLOAT", "true", "false"]
follow = ["*", "/", "+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "&&", "||", "{", ",", "]"]

[id_rest]
prods = [
    ["(", "input_list", ")"],
    ["opt_index"],
    ["::", "id", "id_rest"],
    [".", "id", "id_rest"],
    [""]
]
first = ["(", "[", "::", ".", ""]
follow = ["*", "/", "+", "-", ")", ";", "==", "!=", "<", ">", "<=", ">=", "&&", "||", "{", ",", "]"]

[id]
prods = [
    ["IDENTIFIER"]
]
first = ["IDENTIFIER"]
follow = [")", "+", "-", "*", "/", ";", ":", "=", "(", "{"]

[input_list]
prods = [
    ["cond_or_arr", "input_rest"],
    [""]
]
first = ["(", "IDENTIFIER", "-", "INTEGER", "FLOAT", "true", "false", "CHARACTER", "[", ""]
follow = [")", "]"]

[input_rest]
prods = [
    [",", "input_list"],
    [""]
]
first = [",", ""]
follow = [")", "]"]

[field_list]
prods = [
    ["field", "field_rest"],
    [""]
]
first = ["IDENTIFIER", ""]
follow = ["}"]

[field_rest]
prods = [
    [",", "field_list"],
    [""]
]
first = [",", ""]
follow = ["}"]

[field]
prods = [
    ["id", ":", "value"]
]
first = ["IDENTIFIER"]
follow = [",", "}"]

[conditional]
prods = [
    ["bool_term", "conditional1"]
]
first = ["(", "IDENTIFIER", "-", "INTEGER", "FLOAT", "true", "false", "CHARACTER"]
follow = ["{", ";", ",", ")", "]"]

[conditional1]
prods = [
    ["||", "bool_term", "conditional1"],
    [""]
]
first = ["||", ""]
follow = ["{", ";", ",", ")", "]"]

[bool_term]
prods = [
    ["bool_expr", "bool_term1"]
]

first = ["(", "IDENTIFIER", "-", "INTEGER", "FLOAT", "true", "false", "CHARACTER"]
follow = ["{", "||", ";", ",", ")", "]"]

[bool_term1]
prods = [
    ["&&", "bool_expr", "bool_term1"],
    [""]
]
first = ["||", ""]
follow = ["{", "||", ";", ",", ")", "]"]

[bool_expr]
prods = [
    ["expression", "comparison"],
]
first = ["(", "IDENTIFIER", "-", "INTEGER", "FLOAT", "true", "false", "CHARACTER"]
follow = ["&&", "||", "{", ";", ",", ")", "]"]

[comparison]
prods = [
    ["==", "expression"],
    ["!=", "expression"],
    ["<", "expression"],
    [">", "expression"],
    ["<=", "expression"],
    [">=", "expression"],
    [""]
]
first = ["==", "!=", "<", ">", "<=", ">=", ""]
follow = ["&&", "||", "{", ";", ",", ")", "]"]

[primitive]
prods = [
    ["true"],
    ["false"],
    ["positive"],
    ["-", "positive"],
]
first = ["-", "INTEGER", "FLOAT", "true", "false"]

[positive]
prods = [
    ["INTEGER"],
    ["FLOAT"]
]
first = ["INTEGER", "FLOAT"]

[definition]
prods = [
    ["var", "id", ":", "type", "=", "value", ";"],
    ["const", "id", ":", "type", "=", "value", ";"],
]
first = ["var", "const"]
follow = ["fn", "export", "var", "const", "IDENTIFIER", "while", "if", "return", "}"]

[type]
prods = [
    ["id"],
    ["int"],
    ["float"],
    ["char"],
    ["bool"],
    ["[", "type", ";", "arr_len", "]"],
]
first = ["IDENTIFIER", "int", "float", "char", "bool", "["]
follow = ["=", "{", ";"]

[value]
prods = [
    ["conditional"],
    ["array"],
    ["{", "field_list", "}"]
]
first = ["[", "(", "IDENTIFIER", "-", "INTEGER", "FLOAT", "true", "false", "CHARACTER"]
follow = ["{", ";", ","]

[array]
prods = [
    ["[", "input_list", "]"],
]
first = ["["]

[arr_len]
prods = [
    ["INTEGER"]
]
first = ["INTEGER"]
follow = ["]"]